const countries = [
  { name: "Afghanistan", code: "af", dial: "+93" },
  { name: "Albania", code: "al", dial: "+355" },
  { name: "Algeria", code: "dz", dial: "+213" },
  { name: "Andorra", code: "ad", dial: "+376" },
  { name: "Angola", code: "ao", dial: "+244" },
  { name: "Argentina", code: "ar", dial: "+54" },
  { name: "Armenia", code: "am", dial: "+374" },
  { name: "Australia", code: "au", dial: "+61" },
  { name: "Austria", code: "at", dial: "+43" },
  { name: "Azerbaijan", code: "az", dial: "+994" },

  { name: "Bahamas", code: "bs", dial: "+1-242" },
  { name: "Bahrain", code: "bh", dial: "+973" },
  { name: "Bangladesh", code: "bd", dial: "+880" },
  { name: "Belarus", code: "by", dial: "+375" },
  { name: "Belgium", code: "be", dial: "+32" },
  { name: "Belize", code: "bz", dial: "+501" },
  { name: "Benin", code: "bj", dial: "+229" },
  { name: "Bhutan", code: "bt", dial: "+975" },
  { name: "Bolivia", code: "bo", dial: "+591" },
  { name: "Bosnia and Herzegovina", code: "ba", dial: "+387" },

  { name: "Botswana", code: "bw", dial: "+267" },
  { name: "Brazil", code: "br", dial: "+55" },
  { name: "Brunei", code: "bn", dial: "+673" },
  { name: "Bulgaria", code: "bg", dial: "+359" },
  { name: "Burkina Faso", code: "bf", dial: "+226" },
  { name: "Burundi", code: "bi", dial: "+257" },

  { name: "Cambodia", code: "kh", dial: "+855" },
  { name: "Cameroon", code: "cm", dial: "+237" },
  { name: "Canada", code: "ca", dial: "+1" },
  { name: "Chad", code: "td", dial: "+235" },
  { name: "Chile", code: "cl", dial: "+56" },
  { name: "China", code: "cn", dial: "+86" },
  { name: "Colombia", code: "co", dial: "+57" },
  { name: "Comoros", code: "km", dial: "+269" },
  { name: "Costa Rica", code: "cr", dial: "+506" },
  { name: "Croatia", code: "hr", dial: "+385" },

  { name: "Cuba", code: "cu", dial: "+53" },
  { name: "Cyprus", code: "cy", dial: "+357" },
  { name: "Czech Republic", code: "cz", dial: "+420" },

  { name: "Denmark", code: "dk", dial: "+45" },
  { name: "Djibouti", code: "dj", dial: "+253" },
  { name: "Dominican Republic", code: "do", dial: "+1-809" },

  { name: "Ecuador", code: "ec", dial: "+593" },
  { name: "Egypt", code: "eg", dial: "+20" },
  { name: "El Salvador", code: "sv", dial: "+503" },
  { name: "Eritrea", code: "er", dial: "+291" },
  { name: "Estonia", code: "ee", dial: "+372" },
  { name: "Ethiopia", code: "et", dial: "+251" },

  { name: "Finland", code: "fi", dial: "+358" },
  { name: "France", code: "fr", dial: "+33" },

  { name: "Gabon", code: "ga", dial: "+241" },
  { name: "Gambia", code: "gm", dial: "+220" },
  { name: "Georgia", code: "ge", dial: "+995" },
  { name: "Germany", code: "de", dial: "+49" },
  { name: "Ghana", code: "gh", dial: "+233" },
  { name: "Greece", code: "gr", dial: "+30" },
  { name: "Guatemala", code: "gt", dial: "+502" },
  { name: "Guinea", code: "gn", dial: "+224" },

  { name: "Haiti", code: "ht", dial: "+509" },
  { name: "Honduras", code: "hn", dial: "+504" },
  { name: "Hungary", code: "hu", dial: "+36" },

  { name: "Iceland", code: "is", dial: "+354" },
  { name: "India", code: "in", dial: "+91" },
  { name: "Indonesia", code: "id", dial: "+62" },
  { name: "Iran", code: "ir", dial: "+98" },
  { name: "Iraq", code: "iq", dial: "+964" },
  { name: "Ireland", code: "ie", dial: "+353" },
  { name: "Israel", code: "il", dial: "+972" },
  { name: "Italy", code: "it", dial: "+39" },

  { name: "Japan", code: "jp", dial: "+81" },
  { name: "Jordan", code: "jo", dial: "+962" },

  { name: "Kazakhstan", code: "kz", dial: "+7" },
  { name: "Kenya", code: "ke", dial: "+254" },
  { name: "Kuwait", code: "kw", dial: "+965" },
  { name: "Kyrgyzstan", code: "kg", dial: "+996" },

  { name: "Laos", code: "la", dial: "+856" },
  { name: "Latvia", code: "lv", dial: "+371" },
  { name: "Lebanon", code: "lb", dial: "+961" },
  { name: "Lesotho", code: "ls", dial: "+266" },
  { name: "Liberia", code: "lr", dial: "+231" },
  { name: "Libya", code: "ly", dial: "+218" },
  { name: "Lithuania", code: "lt", dial: "+370" },
  { name: "Luxembourg", code: "lu", dial: "+352" },

  { name: "Madagascar", code: "mg", dial: "+261" },
  { name: "Malawi", code: "mw", dial: "+265" },
  { name: "Malaysia", code: "my", dial: "+60" },
  { name: "Maldives", code: "mv", dial: "+960" },
  { name: "Mali", code: "ml", dial: "+223" },
  { name: "Malta", code: "mt", dial: "+356" },
  { name: "Mexico", code: "mx", dial: "+52" },
  { name: "Moldova", code: "md", dial: "+373" },
  { name: "Mongolia", code: "mn", dial: "+976" },
  { name: "Morocco", code: "ma", dial: "+212" },
  { name: "Mozambique", code: "mz", dial: "+258" },

  { name: "Myanmar", code: "mm", dial: "+95" },

  { name: "Namibia", code: "na", dial: "+264" },
  { name: "Nepal", code: "np", dial: "+977" },
  { name: "Netherlands", code: "nl", dial: "+31" },
  { name: "New Zealand", code: "nz", dial: "+64" },
  { name: "Nicaragua", code: "ni", dial: "+505" },
  { name: "Nigeria", code: "ng", dial: "+234" },
  { name: "North Korea", code: "kp", dial: "+850" },
  { name: "Norway", code: "no", dial: "+47" },

  { name: "Oman", code: "om", dial: "+968" },

  { name: "Pakistan", code: "pk", dial: "+92" },
  { name: "Panama", code: "pa", dial: "+507" },
  { name: "Paraguay", code: "py", dial: "+595" },
  { name: "Peru", code: "pe", dial: "+51" },
  { name: "Philippines", code: "ph", dial: "+63" },
  { name: "Poland", code: "pl", dial: "+48" },
  { name: "Portugal", code: "pt", dial: "+351" },

  { name: "Qatar", code: "qa", dial: "+974" },

  { name: "Romania", code: "ro", dial: "+40" },
  { name: "Russia", code: "ru", dial: "+7" },
  { name: "Rwanda", code: "rw", dial: "+250" },

  { name: "Saudi Arabia", code: "sa", dial: "+966" },
  { name: "Senegal", code: "sn", dial: "+221" },
  { name: "Serbia", code: "rs", dial: "+381" },
  { name: "Singapore", code: "sg", dial: "+65" },
  { name: "Slovakia", code: "sk", dial: "+421" },
  { name: "Slovenia", code: "si", dial: "+386" },
  { name: "Somalia", code: "so", dial: "+252" },
  { name: "South Africa", code: "za", dial: "+27" },
  { name: "South Korea", code: "kr", dial: "+82" },
  { name: "Spain", code: "es", dial: "+34" },
  { name: "Sri Lanka", code: "lk", dial: "+94" },
  { name: "Sudan", code: "sd", dial: "+249" },
  { name: "Sweden", code: "se", dial: "+46" },
  { name: "Switzerland", code: "ch", dial: "+41" },

  { name: "Syria", code: "sy", dial: "+963" },

  { name: "Taiwan", code: "tw", dial: "+886" },
  { name: "Tajikistan", code: "tj", dial: "+992" },
  { name: "Tanzania", code: "tz", dial: "+255" },
  { name: "Thailand", code: "th", dial: "+66" },
  { name: "Tunisia", code: "tn", dial: "+216" },
  { name: "Turkey", code: "tr", dial: "+90" },
  { name: "Turkmenistan", code: "tm", dial: "+993" },

  { name: "Uganda", code: "ug", dial: "+256" },
  { name: "Ukraine", code: "ua", dial: "+380" },
  { name: "United Arab Emirates", code: "ae", dial: "+971" },
  { name: "United Kingdom", code: "gb", dial: "+44" },
  { name: "United States", code: "us", dial: "+1" },
  { name: "Uruguay", code: "uy", dial: "+598" },
  { name: "Uzbekistan", code: "uz", dial: "+998" },

  { name: "Venezuela", code: "ve", dial: "+58" },
  { name: "Vietnam", code: "vn", dial: "+84" },

  { name: "Yemen", code: "ye", dial: "+967" },

  { name: "Zambia", code: "zm", dial: "+260" },
  { name: "Zimbabwe", code: "zw", dial: "+263" },
];

export default countries;
